package flipfit.flipkart.bean;

public class FlipFitCustomer extends FlipFitUser {
    private int customerId;
    static int customerIdCounter = 0;

    public FlipFitCustomer(String name, String email, String username, String password){
        super(name, email, username, password);
        // this is the dummy customer id, actually the customerId will be autogenerated
        this.customerId = customerIdCounter++;
    }

    public int getCustomerId() {
        return customerId;
    }


}
